name: Request support for a specific app
description: We do not take these requests. Please do not make them.
labels: ["issue does not meet guidelines"]
body:
  - type: markdown
    attributes:
      value: |
        We do not take requests to add support for specific apps.
        Please do not make such requests.
