name: Report a bug or regression for a known-working app
description: If an app is already known to work in touchHLE, and no longer works, or has some other problem, choose this option.
labels: ["bug (supported app)"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting an issue with an app that is already known
        to be working in touchHLE. Please check the [app compatibility database](https://appdb.touchhle.org/)
        to see which apps work. Apps with less than three stars are not
        considered “working”.
  - type: input
    attributes:
      label: App DB report link
      description: Link to the pre-existing database report for the app.
    validations:
      required: true
  - type: input
    attributes:
      label: App name
    validations:
      required: true
  - type: input
    attributes:
      label: App version
    validations:
      required: true
  - type: input
    attributes:
      label: touchHLE version
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
  - type: input
    attributes:
      label: GPU
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the problem with the app?
    validations:
      required: true
  - type: textarea
    attributes:
      label: If touchHLE crashed, please paste the log output.
      description: "On Android, this is the log.txt file. On Windows or macOS, it's visible in the Terminal/Command Prompt/PowerShell."
      render: 'text'
